### ISSUE TITLE
Plugin fusion allows to selected more than 6 plugins

### ISSUE THREAD

**Issue by jkoGH** [Umbraculum/Mars-Tomorrow#2]
**Problem**
When I am in the fusion window and want to fusion 6 plugins, after having selected 6 plugins I can further select plugins, and the number in stock decreases. They do not seem to be lost, as after pressing the fusion button, the over-added plugins appear again in stock.

**Expected behavior:** 
After 6 plugins have been added to the fusion, no further plugins should be selectable

**Comment by Umbraculum** [comment]
Fixed with CL2013 Build #600
