### ISSUE TITLE
It is currently possible without warning to replace a truck with exactly the same truck

### ISSUE THREAD

**Issue by jkoGH** [Umbraculum/Mars-Tomorrow#3]
**Problem:**
When a new phase starts and I want to replace my trucks, it may happen, that - by mistake - I replace an already new truck again with a new truck. I do not get a warning message from the game, that this replacement is unnecessary and just a waste of money.

**Expected behavior:**
I want the game to protect me from unwanted replacements of trucks with exactly the same truck.

**Comment by Umbraculum** [comment]
Fixed with CL2014 Build #602
