### ISSUE TITLE
Overflow for high numeric values in Mars Dollar statistics

### ISSUE THREAD

**Issue by jkoGH** [Umbraculum/Mars-Tomorrow#4]
**Environment:**
Browser (chrome)

**Problem:**
When looking at the statistics for Mars dollars, the sums for phase 7 and 8 are sometimes negative. This seems to be a Int32 overflow error. However, the problem does not seem to occur on all servers.

**Expected behavior:**
The sum is calculated and displayed correctly.

**Comment by Umbraculum** [comment]
Fixed with CL2019 Build #608

Scheduled for the next release
