### ISSUE TITLE
Sort order not correct for truck durability in transporters' statistics overview

### ISSUE THREAD

**Issue by jkoGH** [Umbraculum/Mars-Tomorrow#6]
**Environment:**
Browser (Chrome)

**Problem:**
When sorting transporters by durability in the transporters' statistics view, the order is not correct sometimes. Transporters with a difference of 1 % (like 84 and 85% durability) appear in a wrong order, with an 84% transporter between two 85% transporters.

**Expected behavior:**
The order by durability of the transporters should be correct from a mathematical point of view.

**Comment by Umbraculum** [comment]
Fixed with CL2018 Build #607

Scheduled for the next release
